### ISSUE TITLE
Alternate ways of running ArcPy

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/shapefile-to-json#15]

**Comment by sean-eagles** [comment]
Sent off message to Arash in regards to running arcpy/arcgis/arcpro on the cloud.

**Comment by sean-eagles** [comment]
Arash: try running an instance on EC2.
Bruno: buy a license and install it on a VPC/EC2 on the cloud.
Why: From the cloud, an instance of ArcMap cannot reach the license server which is behind the NRCan firewall.  an ArcINFO license would be around $11,000.

**Comment by jvanulde** [comment]
@sean-eagles @arashmalekz is there a way to run these Python functions on a server that is already licensed? For example, we can create a simple flask application or implement an API Gateway? I guess that may not work depending on what the inputs are for a given script... thoughts?

**Comment by sean-eagles** [comment]
Better question for @arashmalekz  or Bruno Avard.  Sent an email to Bruno.

**Comment by sean-eagles** [comment]
Set up in cloud on EC2, license server set up that accesses ArcGIS licenses.  Closed.
